version: 3.7.0-ci{build}

image: Visual Studio 2015

environment:
  matrix:
  - PlatformToolset: Cygwin
  - PlatformToolset: MinGW
    Platform: Win32
    Version: 4.8.5
  - PlatformToolset: MinGW
    Platform: x64
    Version: 4.8.5
  - PlatformToolset: MinGW
    Platform: Win32
    Version: 5.3.0
  - PlatformToolset: MinGW
    Platform: x64
    Version: 5.3.0
  - PlatformToolset: v90
  - PlatformToolset: v100

install:
- ps: if ($env:PlatformToolset -eq 'MinGW') { choco install mingw --version $env:Version $( if ($env:Platform -eq 'Win32') { Write-Output -forcex86 } ) | Out-Null }

build_script:
- ps: scripts\appveyor_ci_build.ps1

test_script:
- ps: scripts\appveyor_ci_test.ps1

artifacts:
- path: lib\CppUTest.lib
  name: CppUTest

# Other configuration options
platform: Win32
configuration: Release
