version: 3.7.0-ci{build}

os:
- Windows Server 2012 R2

environment:
  matrix:
  - PlatformToolset: Cygwin
  - PlatformToolset: MinGW
    Platform: Win32
    Version: 4.8.5
  - PlatformToolset: MinGW
    Platform: x64
    Version: 4.8.5
  - PlatformToolset: MinGW
    Platform: Win32
    Version: 5.3.0
  - PlatformToolset: MinGW
    Platform: x64
    Version: 5.3.0
  - PlatformToolset: v90
  - PlatformToolset: v100

install:
- ps: if ($env:PlatformToolset -eq 'MinGW') { choco install mingw --version $env:Version $( if ($env:Platform -eq 'Win32') { Write-Output -forcex86 } ) | Out-Null }
- ps: if ($env:PlatformToolset -eq 'Cygwin') { . "C:\cygwin\cygwin-setup.exe" -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup --packages autoconf automake make gcc-core libtool gcc-g++ }

build_script:
- ps: scripts\appveyor_ci_build.ps1

test_script:
- ps: scripts\appveyor_ci_test.ps1

artifacts:
- path: lib\CppUTest.lib
  name: CppUTest

# Other configuration options
platform: Win32
configuration: Release
